### ISSUE TITLE
Can not connect to server started by the official docker

### ISSUE THREAD

**Issue by meanna** [JULIELab/smithsearch#9] opened 2024-06-06 14:45 UTC
Hello, 

I run this command
`docker run --rm -p 8080:8080  julielab/smithsearch:1.0.0`

It successfully started a docker container, however when I curl to test the server, it does not work.
```

>>> curl -XPOST http://localhost:8080/search -H 'Content-Type: application/json' -d '{"query":"R05","from":0,"size
":5,"doHighlighting":true,"doFaceting":true}'

{"timestamp":"2024-06-06T14:40:45.644+00:00","status":415,"error":"Unsupported Media Type","path":"/search"}curl: (6) Could not resolve host: application

```

When I go to http://localhost:8080/search on my browser, it says
```
Whitelabel Error Page
This application has no explicit mapping for /error, so you are seeing this as a fallback.

Thu Jun 06 14:43:36 UTC 2024
There was an unexpected error (type=Method Not Allowed, status=405).
```

This is what docker log shows

`
2024-06-06 16:43:36 2024-06-06T14:43:36.739Z  WARN 1 --- [nio-8080-exec-5] .w.s.m.s.DefaultHandlerExceptionResolver : Resolved [org.springframework.web.HttpRequestMethodNotSupportedException: Request method 'GET' is not supported]`

I'm using docker from a Windows machine.

Could you please help me?

**Comment by khituras** [comment] 2024-06-10 07:09
Hello,

did you perhaps start the cURL command from PowerShell? It's just a guess because I can't reproduce the error.

I deleted all my Docker containers, entered the directory `es-docker` and issued the following commands on a Mac 11.7.10 Sierra:
```bash
docker run -d --name elasticsearch-preanalyzed-smith -p 9200:9200 -p 9300:9300 -e "discovery.type=single-node" elasticsearch-preanalyzed-smith:1.0.0
curl -XPUT http://localhost:9200/smith -H 'Content-Type: application/json' -d @../engine/src/main/resources/esMappingFile.json
docker run --rm -p 8080:8080 julielab/smithsearch:1.0.0
curl -XPOST http://localhost:8080/search -H 'Content-Type: application/json' -d '{"query":"R05","from":0,"siz":5,"doHighlighting":true,"doFaceting":true}'
```
The result was
```{"hits":[],"numHits":0,"numHitsRelation":"Eq","entityIdCounts":[]}```
because after a fresh setup the index is empty.

**Comment by meanna** [comment] 2024-06-12 22:08
Hello,

Yes, I run from powershell. After you added `elasticsearch-mapper-preanalyzed-7.17.8.zip`, I can start the service now. 
I also had to adjust the command a little but so that it works on Windows.

Thank you!

**Comment by meanna** [comment] 2024-06-12 22:12
I have another question.

Do you have an example of how I can add documents?

**Comment by khituras** [comment] 2024-06-15 16:45
There is the `indexing-pipeline` in the directory with that very same name. The README file there provides instructions.
Main steps: 
* get the [JCoRe Pipeline Modules](https://github.com/JULIELab/jcore-pipeline-modules); follow the instructions given in the README of the JCoRe Pipeline Modules repository,
* create a dictionary and edit the gazetteer component of the pipeline to use your dictionary. You need to adapt the part that currently says `Resource URL: file:resources/ICD10-2022-reversed.dict`
* point the collection reader of the pipeline to your text files (the part that currently says `InputDirectory: data/files/jsyncc` when viewing the pipeline with the JCoRe Pipeline Builder).
* run the pipeline using the provided `run.xml` file with the JCoRe Pipeline Runner

I know that there hides quite a learning curve behind those instructions. I hope you can follow the README files and the given instructions. You can come back to me in every step, if required. I will close this issue because it has been solved. Feel free to open new issues for further questions.

**Closed** 2024-06-15 16:47 UTC
